# path: ./docker-compose.yml

version: '4'
name: webapp
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - webapp
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
    networks:
      - webapp
  api:
    depends_on:
      - rabbitmq
      - redis
    build:
      context: './WebApplication1'
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8080'
    environment:
      - RabbitMQ__Hostname=rabbitmq
      - Redis__Hostname=redis:6379
    networks:
      - webapp
volumes:
  cache :
networks:
  webapp:
    name: webapp
    driver: bridge
